### PR TITLE
driver SAs do not need to have access to all secrets in the cluster.

### PR DESCRIPTION
**Pull request by obacak**
removes all verbs for secrets from ClusterRoles and creates 2 Roles instead with RoleBindings.
Signed-off-by: Onur Bacak <obacak@epo.org>

### CODE REVIEW

**Review by raunakkumar — APPROVED** [review]
Thanks @obacak. The changes look good to me.

**Comment by obacak** [comment]
> Thanks @obacak. The changes look good to me.

Thanks @raunakkumar, anything I need to do so this can be merged to master?

**Comment by raunakkumar** [comment]
@obacak We need this change in yaml deployment fuless too. The next official version of our helm chart is still a couple of months away. Would the yaml files work for you?

**Comment by obacak** [comment]
@raunakkumar, we do not need this urgently so if it is in the next helm chart release that is OK for us. 
I can also do the changes on the yaml files if you let me know how I should proceed, I see you have multiple folders under [csi-driver](https://github.com/hpe-storage/co-deployments/tree/master/yaml/csi-driver).

**Comment by raunakkumar** [comment]
Sure, the latest yaml files can be found at https://github.com/hpe-storage/co-deployments/tree/master/yaml/csi-driver/edge

**Comment by obacak** [comment]
I am closing this in favour of a new one.

**Pull request closed without merging**
