### PR TITLE
Con 1762 - Increase timeout since cv-csp takes longer to provision

### PR DESCRIPTION
**Pull request by ckallianpur**
@datamattsson - This effects clone. Do we need this for 1.5-beta?

### CODE REVIEW

**Review by raunakkumar — APPROVED** [review]
lgtm

**Review by suneeth51 — APPROVED** [review]
lgtm..

**Review by suneeth51 — CHANGES_REQUESTED** [review]
We may not this change anymore.

**Comment by raunakkumar** [comment]
@suneeth51 can we close this PR?

**Comment by suneeth51** [comment]
We are not supporting CV-CSP

**Pull request closed without merging**
