### PR TITLE
Allow injection of environment variables for containers

### PR DESCRIPTION
**Pull request by papanito**

### CODE REVIEW

**Comment by papanito** [comment]
@raunakkumar @rgcostea @suneeth51 another one. Appreciate your review

**Comment by papanito** [comment]
Any chance this gets into the next release?

**Comment by raunakkumar** [comment]
> Any chance this gets into the next release?

@papanito Any reason why the iscsi target portals to be part of env variables? The CSP creates the initiator group with only the matching network between the storage system and the host known networks.

**Comment by datamattsson** [comment]
@papanito hardcoding portal IPs with Primera/3PAR CSP is done with the "iscsiPortalIps" `StorageClass` parameter:

- https://scod.hpedev.io/container_storage_provider/hpe_3par_primera/index.html#iscsi_target_portal_ip_parameter

I don't really see a broader need to inject environment variables into the CSPs with the Helm chart.

**Comment by papanito** [comment]
The proposal comes from our internal documentation which states
> Since we are using multiple vlans for iscsi which was not supported by the driver, hpe made some changes for us.
>
>This is not implemented in the helm chart at time of writing.
>
>To include this in the helm chart an env variable has to be added to the primera-csp deployment template.

image

**Comment by datamattsson** [comment]
@papanito any reason why using `iscsiPortalIps` in the `StorageClass` would replace this functionality you have in your internal docs?

**Comment by papanito** [comment]
Here the info from the respective support ticket, apparently it's required for particular cases:

> try this new build : `hpestorage/hpe3parprimera-csp:v1.0.1-iscsivlanfix`?
>It introduces a new ENVIRONMENT variable called ISCSI_TARGET_PORTAL_IPS which you need to set the value like for the primera3par-csp-svc service.
> Once set, and CSP pod is restarted, this portal IP’s will be used mount , if it can’t read the Storage class parameters `iscsiPortalIps`
> ```
>spec:
>priorityClassName: system-cluster-critical
>containers:
>- name: primera3par-csp
>#image: hpestorage/hpe3parprimera-csp:v1.0.1-iscsivlanfix
>image: sandanar/hpe_3par_primera_csp:vlanfix
>imagePullPolicy: Always
>env:
>- name: ISCSI_TARGET_PORTAL_IPS
>value: "192.168.68.201,192.168.68.203"
>```
>On successful setting of this variable, the CSP log line would look like
>
>```
>ublish_volume_cmd.go:223"
>time="2020-07-27T06:50:58Z" level=debug msg="ENVIRONMENT ISCSI_TARGET_PORTAL_IPS SET >192.168.68.201,192.168.68.203" file="publish_volume_cmd.go:223
>````
> This will fix the problem with the pod mount for your existing volumes which doesn't get reflected with the volume provisioning parameter `iscsiPortalIps`

Even so this may be a rare case, I believe it would not hurt to merge my changes. I would feel much better if we can use the official chart instead maintain our own modified one.

**Comment by papanito** [comment]
And? Do you think this feature could be added. I really believe it does not hurt but helps special cases like ours. Thanks.

**Comment by suneeth51** [comment]
> And? Do you think this feature could be added. I really believe it does not hurt but helps special cases like ours. Thanks.

@papanito  We already support a well-defined SC parameter `iscsiPortalIps` and that should take care of your issue. However, introducing new ENV variable (just for 3PAR) as an alternative option would not provide a consistent behavior in our ecosystem as we support multiple CSPs like 3PAR, Nimble, etc..

@sneharai4 This can be fixed in the 3PAR CSP if required. Could you please take a look and comment so that we can push that fix in the next release?

**Pull request closed without merging**
