### PR TITLE
Added patch for snapshotter role

### PR DESCRIPTION
**Pull request by bhagyashree-sarawate**
Fix for issue 
I0221 06:30:12.036431       1 event.go:285] Event(v1.ObjectReference{Kind:"VolumeSnapshotContent", Namespace:"", Name:"snapcontent-22de68e8-c1b4-4b15-ac99-f916e326fcd2", UID:"28b4b0c6-95a0-4492-94bc-6ca832a80a51", APIVersion:"snapshot.storage.k8s.io/v1", ResourceVersion:"11279942", FieldPath:""}): type: 'Warning' reason: 'SnapshotCreationFailed' Failed to create snapshot: failed to add VolumeSnapshotBeingCreated annotation on the content snapcontent-22de68e8-c1b4-4b15-ac99-f916e326fcd2: "snapshot controller failed to update snapcontent-22de68e8-c1b4-4b15-ac99-f916e326fcd2 on API server: volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-22de68e8-c1b4-4b15-ac99-f916e326fcd2\" is forbidden: User \"system:serviceaccount:hpe-storage:hpe-csi-controller-sa\" cannot patch resource \"volumesnapshotcontents\" in API group \"snapshot.storage.k8s.io\" at the cluster scope"

### CODE REVIEW

**Review by pavansshanbhag — APPROVED** [review]

**Review by raunakkumar — APPROVED** [review]
Thanks.  Can you check if the roles match the roles for tag v5.0.1 from https://github.com/kubernetes-csi/external-snapshotter/blob/v5.0.1/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml

**Review by raunakkumar — COMMENTED** [review]
also we need to update scod to reflect the correct snapshot controller 
https://github.com/kubernetes-csi/external-snapshotter/tree/v5.0.1/deploy/kubernetes/snapshot-controller @datamattsson  can you help with that ?

**Comment by bhagyashree-sarawate** [comment]
> Thanks. Can you check if the roles match the roles for tag v5.0.1 from https://github.com/kubernetes-csi/external-snapshotter/blob/v5.0.1/deploy/kubernetes/csi-snapshotter/rbac-csi-snapshotter.yaml

yes they match

**Review by raunakkumar — APPROVED** [review]
thanks

**Pull request merged**
