### PR TITLE
Removing crd definitions from raw yamls

### PR DESCRIPTION
**Pull request by bhagyashree-sarawate**
Removing the crd definitions from raw csp file from 2.1.0 onwards

### CODE REVIEW

**Review by raunakkumar — CHANGES_REQUESTED** [review]
Why is this removed from v2.1.0? The release is already out, right?
Should we rather remove from edge?

**Comment by bhagyashree-sarawate** [comment]
If anyone will try to install from this folder which one is out , how should we fix for that?

**Comment by raunakkumar** [comment]
> If anyone will try to install from this folder which one is out , how should we fix for that?

So are you saying we don't need this for 2.1.0 release at all for 1.20-1.22 yamls?

**Comment by bhagyashree-sarawate** [comment]
> 

from https://github.com/hpe-storage/co-deployments/blob/master/yaml/csi-driver/edge/3par-primera-csp.yaml , we should remove
For K8S 1.20-1.22 yamls has only csi-node crds
Also this is required from 2.1.0 onwards

**Comment by raunakkumar** [comment]
> > 
> 
> from https://github.com/hpe-storage/co-deployments/blob/master/yaml/csi-driver/edge/3par-primera-csp.yaml , we should remove For K8S 1.20-1.22 yamls has only csi-node crds Also this is required from 2.1.0 onwards
> 
> For manual installation one has to do from kubectl create -f https://raw.githubusercontent.com/hpe-storage/co-deployments/master/helm/charts/hpe-csi-driver/crds/hpevolumeinfos_v2_crd.yaml kubectl create -f https://raw.githubusercontent.com/hpe-storage/co-deployments/master/helm/charts/hpe-csi-driver/crds/hpevolumegroupinfos_v2_crd.yaml kubectl create -f https://raw.githubusercontent.com/hpe-storage/co-deployments/master/helm/charts/hpe-csi-driver/crds/snapshotgroupinfos_v2_crd.yaml kubectl create -f https://raw.githubusercontent.com/hpe-storage/co-deployments/master/helm/charts/hpe-csi-driver/crds/hpereplicated_deviceinfo_v2_crd.yaml

Thanks. Will merge this then

**Review by raunakkumar — APPROVED** [review]

**Pull request merged**
